### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by ejain** [qos-ch/logback-extensions#1]
Would be useful if the artifacts of this project were published to Maven Central.

**Comment by keyuraashra** [comment]
Hello,

I am working on Android Native app and trying to integrate logback with Loggly, I have successfully integrated it with LogcatAppender but somehow its not working with Loggly.

build.gradle :-
compile 'org.logback-extensions:logback-ext-loggly:0.1.2'

logback.xml :-

<configuration>
    <appender name="LOGCAT" class="ch.qos.logback.classic.android.LogcatAppender">
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>

    <appender name="loggly" class="ch.qos.logback.ext.loggly.LogglyAppender">
        <endpointUrl>https://logs-01.loggly.com/inputs/MY_TOKEN/tag/logback
        </endpointUrl>
        <encoder>
            <pattern>%d{"ISO8601", UTC}  %p %t %c{0}.%M - %m%n</pattern>
        </encoder>
    </appender>

    
    <root level="DEBUG">
        <appender-ref ref="LOGCAT" />
        <appender-ref ref="loggly" />
    </root>
</configuration>

Error :-

08-12 08:44:58.482    5155-5155/co.librarytest I/System.out﹕ 08:44:58,450 |-ERROR in ch.qos.logback.core.joran.action.AppenderAction - Could not create an Appender of type [ch.qos.logback.ext.loggly.LogglyAppender]. ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type ch.qos.logback.ext.loggly.LogglyAppender

Any idea what is going wrong here?

**Comment by tony19** [comment]
@keyuraashra, please create a new GitHub issue for your question, since it has nothing to do this with this ticket. Thanks

**Comment by keyuraashra** [comment]
@tony19 Thanks Tony, will create new one.
