### ISSUE TITLE
Log Events Sent in Batch Mode are not Recognized as Individual Events by Loggly

### ISSUE THREAD

**Issue by MusikPolice** [qos-ch/logback-extensions#17]
I set up a LogglyBatchAppender to ship my logs off to Loggly with the following configuration:

```
<!-- loggly appender running in batch mode -->
<appender name="LOGGLY" class="ch.qos.logback.ext.loggly.LogglyBatchAppender">
    <!-- with this notation, we can manually specify if logs should be reported over http for debugging or https for prod environments -->
    <endpointUrl>http://logs-01.loggly.com/bulk/customer-key</endpointUrl>
    <!-- format logs as JSON so that stack traces are preserved -->
    <layout class="ch.qos.logback.contrib.json.classic.JsonLayout">
        <jsonFormatter class="ch.qos.logback.contrib.jackson.JacksonJsonFormatter"/>
    </layout>
    <!-- performance tuning options -->
    <maxNumberOfBuckets>8</maxNumberOfBuckets>
    <maxBucketSizeInKilobytes>1024</maxBucketSizeInKilobytes>
    <flushIntervalInSeconds>5</flushIntervalInSeconds>
</appender>
```

This works as expected, but when the logs arrive in Loggly, the entire batch is treated as a single event. Here is an example from Loggly's dashboard:
    2014/02/25 21:26:03.213 UTC {"timestamp":"1393363558399","level":"INFO","thread":"main","logger":"org.springframework.web.context.ContextLoader","message":"Root WebApplicationContext: initialization started","context":"default"}    {"timestamp":"1393363558484","level":"INFO","thread":"main","logger":"org.springframework.web.context.support.XmlWebApplicationContext","message":"Refreshing Root WebApplicationContext: startup date [Tue Feb 25 16:25:58 EST 2014]; root of context hierarchy","context":"default"}    {"timestamp":"1393363558519","level":"INFO","thread":"main","logger":"org.springframework.beans.factory.xml.XmlBeanDefinitionReader","message":"Loading XML bean definitions from ServletContext resource [/WEB-INF/spring/applicationContext.xml]","context":"default"}

As you can see, this batch contains three separate log events, but Loggly treats them as a single event.

[According to the Loggly documentation](https://www.loggly.com/docs/api-sending-data/#bulk), individual log events must be separated by newline characters in the POST body of the request. I suspect that this is not being done in the encoder.

**Comment by pathikrit** [comment]
Can we release this as 0.1.3 to maven? I believe Maven still has the old buggy 0.1.2 only: http://mvnrepository.com/artifact/org.logback-extensions/logback-ext-loggly

**Comment by tony19** [comment]
@pathikrit 0.1.3 should be available now via Maven Central. The search interface may take a few hours to index the new version.
