### ISSUE TITLE
if WebLogbackConfigurer use ServletContextPropertyUtils like Log4jWebConfigurer to  resolvePlaceholders is better

### ISSUE THREAD

**Issue by venusdrogon** [qos-ch/logback-extensions#31]
if WebLogbackConfigurer use ServletContextPropertyUtils instead of SystemPropertyUtils like Log4jWebConfigurer to  resolvePlaceholders is better

**Comment by tony19** [comment]
I think you're suggesting a code improvement, but I need more context. Can you provide a link to a source file and clarify a bit? Thanks

**Comment by venusdrogon** [comment]
haha

https://github.com/qos-ch/logback-extensions/pull/27/commits/77348a0201497ae2fd58927cb03b1f1d3009fc38

has fix these question

**Comment by kapad** [comment]
Yup. I actually saw this open issue, and then just submitted a PR. :stuck_out_tongue_closed_eyes:

**Comment by venusdrogon** [comment]
good job
