### ISSUE TITLE
Improve your wiki

### ISSUE THREAD

**Issue by amitkix** [qos-ch/logback-extensions#32]
Hey,

In the last two days I tried to use your LogglyBatchAppender instead of LogglyAppender with no success.

I found my problem just now:
On the 'logback.xml' I used the 'inputKey' tag for declaring my Loggly token and tags.
After a lot of searching I found this [post](https://github.com/qos-ch/logback-extensions/issues/17) that helped me to understand that I should prefer use the 'endpointUrl' tag instead of 'inputKey' tag to specify the route of 'bulk' instead of 'inputs' in the URL between the domain and my token, examples:
```
* BAD: <endpointUrl>https://logs-01.loggly.com/inputs/TOKEN/tag/TAGS</endpointUrl>
* GOOD: <endpointUrl>https://logs-01.loggly.com/bulk/TOKEN/tag/TAGS</endpointUrl>
```

My request for you is to improve the description of property 'endpointUrl' [here](https://github.com/qos-ch/logback-extensions/wiki/Loggly#configuration-settings) to use 'bulk' instead of 'inputs' while using [Batch Mode](https://github.com/qos-ch/logback-extensions/wiki/Loggly#batched-mode).

I hope it'd help a lot of people.

Thanks,
Amit.

**Comment by lukevenediger** [comment]
Thanks Amit - I'd been battling with this issue for hours. Definitely needs better documentation!

**Comment by tony19** [comment]
Ok done
