### ISSUE TITLE
Using Async Mode

### ISSUE THREAD

**Issue by Karnifexx** [qos-ch/logback-extensions#35]
It mentions in the loggly documentation that this logger supports async mode:

https://www.loggly.com/docs/loggly-libraries-catalog/

I have been unable to determine however how to activate this async mode. A guide pointer to any existing documentation would be greatly appreciated.

**Comment by tony19** [comment]
[`LogbackBatchAppender`](https://github.com/qos-ch/logback-extensions/wiki/Loggly#batched-mode) works asynchronously by default, so to use "async mode" would be to use that appender (instead of `LogglyAppender`).
