### ISSUE TITLE
Severe vulnerability requires logback version upgrade

### ISSUE THREAD

**Issue by cdanger** [qos-ch/logback-extensions#49]
Hello, 
logback News page says _Release 1.2.0 fixes a rather severe serialization vulnerability in SocketServer and ServerSocketReceiver. Users running these components should upgrade immediately._ Therefore, could you make a new release with logback.version >= 1.2.0 ? 
It is 1.1.1 currently :-(

**Comment by cdanger** [comment]
If you allow me as Contributor, I could do it. Maybe I would need some permission on Maven Central as well to publish the release.

**Comment by tony19** [comment]
Fixed in [0.1.5](https://github.com/qos-ch/logback-extensions/releases/tag/v_0.1.5)
